name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Does Compile
      id: does-compile
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Does Compile
        setup-command: cd './App' && npm install
        command: npm run build
        timeout: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DOES-COMPILE_RESULTS: "${{steps.does-compile.outputs.result}}"
      with:
        runners: does-compile
